-- MySQL Script generated by MySQL Workbench
-- Tue Sep 26 08:42:33 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Destinacija`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Destinacija` (
  `id_Destinacija` INT NOT NULL,
  `kraj` VARCHAR(45) NOT NULL,
  `drzava` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_Destinacija`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Vodja`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Vodja` (
  `maticna_stevilka` VARCHAR(15) NOT NULL,
  `ime` VARCHAR(45) NOT NULL,
  `priimek` VARCHAR(45) NOT NULL,
  `izobrazba` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`maticna_stevilka`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Paket_potovanja`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Paket_potovanja` (
  `idPaket_potovanja` INT NOT NULL,
  `opis` VARCHAR(45) NOT NULL,
  `cena` FLOAT NOT NULL,
  PRIMARY KEY (`idPaket_potovanja`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Potovanje`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Potovanje` (
  `Paket_potovanja_idPaket_potovanja` INT NOT NULL,
  `od` DATE NOT NULL,
  `do` DATE NOT NULL,
  `Vodja_maticna_stevilka` VARCHAR(15) NOT NULL,
  INDEX `fk_Potovanje_Vodja1_idx` (`Vodja_maticna_stevilka` ASC) VISIBLE,
  PRIMARY KEY (`Paket_potovanja_idPaket_potovanja`, `od`, `do`),
  INDEX `fk_Potovanje_Paket_potovanja1_idx` (`Paket_potovanja_idPaket_potovanja` ASC) VISIBLE,
  CONSTRAINT `fk_Potovanje_Vodja1`
    FOREIGN KEY (`Vodja_maticna_stevilka`)
    REFERENCES `mydb`.`Vodja` (`maticna_stevilka`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Potovanje_Paket_potovanja1`
    FOREIGN KEY (`Paket_potovanja_idPaket_potovanja`)
    REFERENCES `mydb`.`Paket_potovanja` (`idPaket_potovanja`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Nacin_prevoza`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Nacin_prevoza` (
  `naziv` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`naziv`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Destinacija_na_Potovanju`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Destinacija_na_Potovanju` (
  `Destinacija_id_Destinacija` INT NOT NULL,
  `Nacin_prevoza_naziv` VARCHAR(45) NOT NULL,
  `Paket_potovanja_idPaket_potovanja` INT NOT NULL,
  PRIMARY KEY (`Destinacija_id_Destinacija`, `Paket_potovanja_idPaket_potovanja`),
  INDEX `fk_Destinacija_has_Potovanje_Destinacija_idx` (`Destinacija_id_Destinacija` ASC) VISIBLE,
  INDEX `fk_Destinacija_na_Potovanju_Nacin_prevoza1_idx` (`Nacin_prevoza_naziv` ASC) VISIBLE,
  INDEX `fk_Destinacija_na_Potovanju_Paket_potovanja1_idx` (`Paket_potovanja_idPaket_potovanja` ASC) VISIBLE,
  CONSTRAINT `fk_Destinacija_has_Potovanje_Destinacija`
    FOREIGN KEY (`Destinacija_id_Destinacija`)
    REFERENCES `mydb`.`Destinacija` (`id_Destinacija`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Destinacija_na_Potovanju_Nacin_prevoza1`
    FOREIGN KEY (`Nacin_prevoza_naziv`)
    REFERENCES `mydb`.`Nacin_prevoza` (`naziv`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Destinacija_na_Potovanju_Paket_potovanja1`
    FOREIGN KEY (`Paket_potovanja_idPaket_potovanja`)
    REFERENCES `mydb`.`Paket_potovanja` (`idPaket_potovanja`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Dejanski_prevoz`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Dejanski_prevoz` (
  `odhod` TIMESTAMP NOT NULL,
  `prihod` TIMESTAMP NOT NULL,
  `Potovanje_Paket_potovanja_idPaket_potovanja` INT NOT NULL,
  `Potovanje_od` DATE NOT NULL,
  `Potovanje_do` DATE NOT NULL,
  `Destinacija_na_Potovanju_Destinacija_id_Destinacija` INT NOT NULL,
  `Destinacija_na_Potovanju_Paket_potovanja_idPaket_potovanja` INT NOT NULL,
  PRIMARY KEY (`Potovanje_Paket_potovanja_idPaket_potovanja`, `Potovanje_od`, `Potovanje_do`, `Destinacija_na_Potovanju_Destinacija_id_Destinacija`, `Destinacija_na_Potovanju_Paket_potovanja_idPaket_potovanja`),
  INDEX `fk_Dejanski_prevoz_Destinacija_na_Potovanju1_idx` (`Destinacija_na_Potovanju_Destinacija_id_Destinacija` ASC, `Destinacija_na_Potovanju_Paket_potovanja_idPaket_potovanja` ASC) VISIBLE,
  CONSTRAINT `fk_Dejanski_prevoz_Potovanje1`
    FOREIGN KEY (`Potovanje_Paket_potovanja_idPaket_potovanja` , `Potovanje_od` , `Potovanje_do`)
    REFERENCES `mydb`.`Potovanje` (`Paket_potovanja_idPaket_potovanja` , `od` , `do`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Dejanski_prevoz_Destinacija_na_Potovanju1`
    FOREIGN KEY (`Destinacija_na_Potovanju_Destinacija_id_Destinacija` , `Destinacija_na_Potovanju_Paket_potovanja_idPaket_potovanja`)
    REFERENCES `mydb`.`Destinacija_na_Potovanju` (`Destinacija_id_Destinacija` , `Paket_potovanja_idPaket_potovanja`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
