-- MySQL Script generated by MySQL Workbench
-- Tue Sep 26 07:59:02 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`spletne_strani`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`spletne_strani` (
  `id_spletne_strani` VARCHAR(250) NOT NULL,
  `opis` VARCHAR(250) NOT NULL,
  `admin` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`id_spletne_strani`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Zvrst`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Zvrst` (
  `naziv` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`naziv`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`jedi`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`jedi` (
  `id_jedi` INT NOT NULL,
  `naziv` VARCHAR(45) NOT NULL,
  `opis` VARCHAR(45) NOT NULL,
  `Zvrst_naziv` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_jedi`),
  INDEX `fk_jedi_Zvrst_idx` (`Zvrst_naziv` ASC) VISIBLE,
  CONSTRAINT `fk_jedi_Zvrst`
    FOREIGN KEY (`Zvrst_naziv`)
    REFERENCES `mydb`.`Zvrst` (`naziv`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Uporabniki`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Uporabniki` (
  `id_Uporabniki` INT NOT NULL,
  `uporabnisko_ime` VARCHAR(45) NOT NULL,
  `geslo` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_Uporabniki`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Sestavine`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Sestavine` (
  `id_Sestavine` INT NOT NULL,
  `naziv` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_Sestavine`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Recepti`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Recepti` (
  `id_Recepti` INT NOT NULL,
  `postopek` MEDIUMTEXT NOT NULL,
  `jedi_id_jedi` INT NOT NULL,
  `Uporabniki_id_Uporabniki` INT NOT NULL,
  PRIMARY KEY (`id_Recepti`),
  INDEX `fk_Recepti_jedi1_idx` (`jedi_id_jedi` ASC) VISIBLE,
  INDEX `fk_Recepti_Uporabniki1_idx` (`Uporabniki_id_Uporabniki` ASC) VISIBLE,
  CONSTRAINT `fk_Recepti_jedi1`
    FOREIGN KEY (`jedi_id_jedi`)
    REFERENCES `mydb`.`jedi` (`id_jedi`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Recepti_Uporabniki1`
    FOREIGN KEY (`Uporabniki_id_Uporabniki`)
    REFERENCES `mydb`.`Uporabniki` (`id_Uporabniki`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Sestavine_v_Receptu`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Sestavine_v_Receptu` (
  `Sestavine_id_Sestavine` INT NOT NULL,
  `Recepti_id_Recepti` INT NOT NULL,
  `kolicina` FLOAT NOT NULL,
  PRIMARY KEY (`Sestavine_id_Sestavine`, `Recepti_id_Recepti`),
  INDEX `fk_Sestavine_has_Recepti_Recepti1_idx` (`Recepti_id_Recepti` ASC) VISIBLE,
  INDEX `fk_Sestavine_has_Recepti_Sestavine1_idx` (`Sestavine_id_Sestavine` ASC) VISIBLE,
  CONSTRAINT `fk_Sestavine_has_Recepti_Sestavine1`
    FOREIGN KEY (`Sestavine_id_Sestavine`)
    REFERENCES `mydb`.`Sestavine` (`id_Sestavine`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Sestavine_has_Recepti_Recepti1`
    FOREIGN KEY (`Recepti_id_Recepti`)
    REFERENCES `mydb`.`Recepti` (`id_Recepti`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`mnenje_o_receptu`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`mnenje_o_receptu` (
  `Uporabniki_id_Uporabniki` INT NOT NULL,
  `Recepti_id_Recepti` INT NOT NULL,
  `ocena` INT NOT NULL,
  `komentar` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`Uporabniki_id_Uporabniki`, `Recepti_id_Recepti`),
  INDEX `fk_Uporabniki_has_Recepti_Recepti2_idx` (`Recepti_id_Recepti` ASC) VISIBLE,
  INDEX `fk_Uporabniki_has_Recepti_Uporabniki2_idx` (`Uporabniki_id_Uporabniki` ASC) VISIBLE,
  CONSTRAINT `fk_Uporabniki_has_Recepti_Uporabniki2`
    FOREIGN KEY (`Uporabniki_id_Uporabniki`)
    REFERENCES `mydb`.`Uporabniki` (`id_Uporabniki`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Uporabniki_has_Recepti_Recepti2`
    FOREIGN KEY (`Recepti_id_Recepti`)
    REFERENCES `mydb`.`Recepti` (`id_Recepti`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Recepti_na_spletne_strani`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Recepti_na_spletne_strani` (
  `Recepti_id_Recepti` INT NOT NULL,
  `spletne_strani_id_spletne_strani` VARCHAR(250) NOT NULL,
  PRIMARY KEY (`Recepti_id_Recepti`, `spletne_strani_id_spletne_strani`),
  INDEX `fk_Recepti_has_spletne_strani_spletne_strani1_idx` (`spletne_strani_id_spletne_strani` ASC) VISIBLE,
  INDEX `fk_Recepti_has_spletne_strani_Recepti1_idx` (`Recepti_id_Recepti` ASC) VISIBLE,
  CONSTRAINT `fk_Recepti_has_spletne_strani_Recepti1`
    FOREIGN KEY (`Recepti_id_Recepti`)
    REFERENCES `mydb`.`Recepti` (`id_Recepti`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Recepti_has_spletne_strani_spletne_strani1`
    FOREIGN KEY (`spletne_strani_id_spletne_strani`)
    REFERENCES `mydb`.`spletne_strani` (`id_spletne_strani`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
