-- MySQL Script generated by MySQL Workbench
-- Fri Sep 15 21:36:57 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Repertoar`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Repertoar` (
  `idRepertoar` INT NOT NULL,
  `datum` DATE NOT NULL,
  PRIMARY KEY (`idRepertoar`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Pevci`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Pevci` (
  `idPevci` INT NOT NULL,
  `ime` VARCHAR(15) NOT NULL,
  `priimek` VARCHAR(15) NOT NULL,
  `zivljenjepis` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`idPevci`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Reziser`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Reziser` (
  `idReziser` INT NOT NULL,
  `ime` VARCHAR(45) NOT NULL,
  `priimek` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idReziser`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Predstave`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Predstave` (
  `idPredstave` INT NOT NULL,
  `ime` VARCHAR(45) NOT NULL,
  `zvrst` VARCHAR(20) NOT NULL,
  `imeAvtorja` VARCHAR(45) NOT NULL,
  `Solisti_idSolisti` INT NOT NULL,
  `Pevci_idPevci` INT NOT NULL,
  `Reziser_idReziser` INT NOT NULL,
  PRIMARY KEY (`idPredstave`),
  INDEX `fk_Predstave_Pevci1_idx` (`Pevci_idPevci` ASC) VISIBLE,
  INDEX `fk_Predstave_Reziser1_idx` (`Reziser_idReziser` ASC) VISIBLE,
  CONSTRAINT `fk_Predstave_Pevci1`
    FOREIGN KEY (`Pevci_idPevci`)
    REFERENCES `mydb`.`Pevci` (`idPevci`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Predstave_Reziser1`
    FOREIGN KEY (`Reziser_idReziser`)
    REFERENCES `mydb`.`Reziser` (`idReziser`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Repertoar_has_Predstave`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Repertoar_has_Predstave` (
  `Repertoar_idRepertoar` INT NOT NULL,
  `Predstave_idPredstave` INT NOT NULL,
  `casZacetka` DATETIME NOT NULL,
  `casKonca` DATETIME NOT NULL,
  `zasedba` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`Repertoar_idRepertoar`, `Predstave_idPredstave`),
  INDEX `fk_Repertoar_has_Predstave_Predstave1_idx` (`Predstave_idPredstave` ASC) VISIBLE,
  INDEX `fk_Repertoar_has_Predstave_Repertoar_idx` (`Repertoar_idRepertoar` ASC) VISIBLE,
  CONSTRAINT `fk_Repertoar_has_Predstave_Repertoar`
    FOREIGN KEY (`Repertoar_idRepertoar`)
    REFERENCES `mydb`.`Repertoar` (`idRepertoar`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Repertoar_has_Predstave_Predstave1`
    FOREIGN KEY (`Predstave_idPredstave`)
    REFERENCES `mydb`.`Predstave` (`idPredstave`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Pevci_na_predstavi`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Pevci_na_predstavi` (
  `Pevci_idPevci` INT NOT NULL,
  `Predstave_idPredstave` INT NOT NULL,
  `vloga` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`Pevci_idPevci`, `Predstave_idPredstave`),
  INDEX `fk_Predstave_has_Pevci_Pevci1_idx` (`Pevci_idPevci` ASC) VISIBLE,
  INDEX `fk_Pevci_na_predstavi_Predstave1_idx` (`Predstave_idPredstave` ASC) VISIBLE,
  CONSTRAINT `fk_Predstave_has_Pevci_Pevci1`
    FOREIGN KEY (`Pevci_idPevci`)
    REFERENCES `mydb`.`Pevci` (`idPevci`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Pevci_na_predstavi_Predstave1`
    FOREIGN KEY (`Predstave_idPredstave`)
    REFERENCES `mydb`.`Predstave` (`idPredstave`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
