-- MySQL Script generated by MySQL Workbench
-- Fri Sep 15 21:32:50 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Zavarovalnice`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Zavarovalnice` (
  `id_zavarovalnice` INT NOT NULL,
  `ime` VARCHAR(45) NOT NULL,
  `naslov` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_zavarovalnice`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Zavarovalne_ police`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Zavarovalne_ police` (
  `id_zavarovalne_police` INT NOT NULL,
  `datumSklenitve` DATETIME NOT NULL,
  `datumVeljavnosti` DATETIME NOT NULL,
  `vrstaZavarovanja` VARCHAR(45) NOT NULL,
  `Zavarovalnice_id_zavarovalnice` INT NOT NULL,
  PRIMARY KEY (`id_zavarovalne_police`, `Zavarovalnice_id_zavarovalnice`),
  INDEX `fk_Zavarovalna polica_Zavarovalnice1_idx` (`Zavarovalnice_id_zavarovalnice` ASC) VISIBLE,
  CONSTRAINT `fk_Zavarovalna polica_Zavarovalnice1`
    FOREIGN KEY (`Zavarovalnice_id_zavarovalnice`)
    REFERENCES `mydb`.`Zavarovalnice` (`id_zavarovalnice`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Bolnik`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Bolnik` (
  `idBolnik` INT NOT NULL,
  `davcnaStevilka` INT NOT NULL,
  `ime` VARCHAR(15) NOT NULL,
  `priimek` VARCHAR(15) NOT NULL,
  `naslov` VARCHAR(45) NOT NULL,
  `datumRojstva` DATETIME NOT NULL,
  `Zavarovalne_ police_id_zavarovalne_police` INT NOT NULL,
  `Zavarovalne_ police_Zavarovalnice_id_zavarovalnice` INT NOT NULL,
  PRIMARY KEY (`idBolnik`),
  INDEX `fk_Bolnik_Zavarovalne_ police1_idx` (`Zavarovalne_ police_id_zavarovalne_police` ASC, `Zavarovalne_ police_Zavarovalnice_id_zavarovalnice` ASC) VISIBLE,
  CONSTRAINT `fk_Bolnik_Zavarovalne_ police1`
    FOREIGN KEY (`Zavarovalne_ police_id_zavarovalne_police` , `Zavarovalne_ police_Zavarovalnice_id_zavarovalnice`)
    REFERENCES `mydb`.`Zavarovalne_ police` (`id_zavarovalne_police` , `Zavarovalnice_id_zavarovalnice`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Zdravnik`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Zdravnik` (
  `idZdravnik` INT NOT NULL,
  `ime` VARCHAR(20) NOT NULL,
  `priimek` VARCHAR(20) NOT NULL,
  `izobrazba` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idZdravnik`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`obiski`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`obiski` (
  `danObiska` DATE NOT NULL,
  `Bolnik_idBolnik` INT NOT NULL,
  `simptomi` VARCHAR(45) NULL,
  `ugotovljenaDiagnoza` VARCHAR(45) NULL,
  `drugo` VARCHAR(255) NULL,
  `izdanRecept` VARCHAR(100) NULL,
  `Zdravnik_idZdravnik` INT NOT NULL,
  `Bolnik_idBolnik1` INT NOT NULL,
  PRIMARY KEY (`Bolnik_idBolnik`, `danObiska`, `Zdravnik_idZdravnik`, `Bolnik_idBolnik1`),
  INDEX `fk_obiski_Zdravnik1_idx` (`Zdravnik_idZdravnik` ASC) VISIBLE,
  INDEX `fk_obiski_Bolnik1_idx` (`Bolnik_idBolnik1` ASC) VISIBLE,
  CONSTRAINT `fk_obiski_Zdravnik1`
    FOREIGN KEY (`Zdravnik_idZdravnik`)
    REFERENCES `mydb`.`Zdravnik` (`idZdravnik`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_obiski_Bolnik1`
    FOREIGN KEY (`Bolnik_idBolnik1`)
    REFERENCES `mydb`.`Bolnik` (`idBolnik`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Recepti`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Recepti` (
  `id_recepti` INT NOT NULL,
  `obiski_Bolnik_idBolnik` INT NOT NULL,
  `obiski_danObiska` DATE NOT NULL,
  `obiski_Zdravnik_idZdravnik` INT NOT NULL,
  `obiski_Bolnik_idBolnik1` INT NOT NULL,
  PRIMARY KEY (`id_recepti`, `obiski_Bolnik_idBolnik`, `obiski_danObiska`, `obiski_Zdravnik_idZdravnik`, `obiski_Bolnik_idBolnik1`),
  INDEX `fk_Recepti_obiski1_idx` (`obiski_Bolnik_idBolnik` ASC, `obiski_danObiska` ASC, `obiski_Zdravnik_idZdravnik` ASC, `obiski_Bolnik_idBolnik1` ASC) VISIBLE,
  CONSTRAINT `fk_Recepti_obiski1`
    FOREIGN KEY (`obiski_Bolnik_idBolnik` , `obiski_danObiska` , `obiski_Zdravnik_idZdravnik` , `obiski_Bolnik_idBolnik1`)
    REFERENCES `mydb`.`obiski` (`Bolnik_idBolnik` , `danObiska` , `Zdravnik_idZdravnik` , `Bolnik_idBolnik1`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Zdravila`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Zdravila` (
  `id_zdravila` INT NOT NULL,
  `ime` VARCHAR(20) NOT NULL,
  `prozivajalec` VARCHAR(20) NOT NULL,
  `kategorijaBolezni` VARCHAR(30) NOT NULL,
  `oznaka` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`id_zdravila`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Recepti_has_Zdravila`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Recepti_has_Zdravila` (
  `Zdravila_id_zdravila` INT NOT NULL,
  `kolicina` FLOAT NOT NULL,
  `naObdobje` VARCHAR(45) NOT NULL,
  `opombe` VARCHAR(100) NULL,
  `Recepti_id_recepti` INT NOT NULL,
  PRIMARY KEY (`Zdravila_id_zdravila`, `Recepti_id_recepti`),
  INDEX `fk_Recepti_has_Zdravila_Zdravila1_idx` (`Zdravila_id_zdravila` ASC) VISIBLE,
  INDEX `fk_Recepti_has_Zdravila_Recepti1_idx` (`Recepti_id_recepti` ASC) VISIBLE,
  CONSTRAINT `fk_Recepti_has_Zdravila_Zdravila1`
    FOREIGN KEY (`Zdravila_id_zdravila`)
    REFERENCES `mydb`.`Zdravila` (`id_zdravila`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Recepti_has_Zdravila_Recepti1`
    FOREIGN KEY (`Recepti_id_recepti`)
    REFERENCES `mydb`.`Recepti` (`id_recepti`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
