-- MySQL Script generated by MySQL Workbench
-- Fri Sep 15 21:43:28 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Proizvajalci`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Proizvajalci` (
  `idProizvajalci` INT NOT NULL,
  `naziv` VARCHAR(45) NOT NULL,
  `poreklo` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idProizvajalci`))
ENGINE = InnoDB
COMMENT = '		';


-- -----------------------------------------------------
-- Table `mydb`.`Komponente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Komponente` (
  `idKomponente` INT NOT NULL,
  `Proizvajalci_idProizvajalci` INT NOT NULL,
  `naziv` VARCHAR(45) NOT NULL,
  `opis` VARCHAR(45) NOT NULL,
  `ocena` FLOAT NULL,
  PRIMARY KEY (`idKomponente`),
  INDEX `fk_Komponente_Proizvajalci1_idx` (`Proizvajalci_idProizvajalci` ASC) VISIBLE,
  CONSTRAINT `fk_Komponente_Proizvajalci1`
    FOREIGN KEY (`Proizvajalci_idProizvajalci`)
    REFERENCES `mydb`.`Proizvajalci` (`idProizvajalci`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Kompleti`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Kompleti` (
  `idKompleti` INT NOT NULL,
  `naziv` VARCHAR(45) NOT NULL,
  `opis` VARCHAR(250) NOT NULL,
  `cena` FLOAT NOT NULL,
  PRIMARY KEY (`idKompleti`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Komponente_v_Kompleti`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Komponente_v_Kompleti` (
  `Komponente_idKomponente` INT NOT NULL,
  `Kompleti_idKompleti` INT NOT NULL,
  PRIMARY KEY (`Komponente_idKomponente`, `Kompleti_idKompleti`),
  INDEX `fk_Komponente_has_Kompleti_Kompleti1_idx` (`Kompleti_idKompleti` ASC) VISIBLE,
  INDEX `fk_Komponente_has_Kompleti_Komponente1_idx` (`Komponente_idKomponente` ASC) VISIBLE,
  CONSTRAINT `fk_Komponente_has_Kompleti_Komponente1`
    FOREIGN KEY (`Komponente_idKomponente`)
    REFERENCES `mydb`.`Komponente` (`idKomponente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Komponente_has_Kompleti_Kompleti1`
    FOREIGN KEY (`Kompleti_idKompleti`)
    REFERENCES `mydb`.`Kompleti` (`idKompleti`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Stranke`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Stranke` (
  `idStranke` INT NOT NULL,
  `EMSO` CHAR(11) NOT NULL,
  `ime` VARCHAR(12) NOT NULL,
  `priimek` VARCHAR(45) NOT NULL,
  `GSM` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idStranke`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Nacin Placila`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Nacin Placila` (
  `idNacin Placila` INT NOT NULL,
  `ime` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idNacin Placila`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Racun`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Racun` (
  `idRacun` INT NOT NULL,
  `datumNakupa` DATETIME NOT NULL,
  `nacinPlacila` VARCHAR(45) NOT NULL,
  `skupnaCena` VARCHAR(45) NOT NULL,
  `Nacin Placila_idNacin Placila1` INT NOT NULL,
  `Stranke_idStranke` INT NOT NULL,
  PRIMARY KEY (`idRacun`),
  INDEX `fk_Racun_Nacin Placila1_idx` (`Nacin Placila_idNacin Placila1` ASC) VISIBLE,
  INDEX `fk_Racun_Stranke1_idx` (`Stranke_idStranke` ASC) VISIBLE,
  CONSTRAINT `fk_Racun_Nacin Placila1`
    FOREIGN KEY (`Nacin Placila_idNacin Placila1`)
    REFERENCES `mydb`.`Nacin Placila` (`idNacin Placila`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Racun_Stranke1`
    FOREIGN KEY (`Stranke_idStranke`)
    REFERENCES `mydb`.`Stranke` (`idStranke`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Postavke`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Postavke` (
  `Kompleti_idKompleti` INT NOT NULL,
  `stevilo` INT NOT NULL,
  `popust` INT NULL,
  `Racun_idRacun` INT NOT NULL,
  PRIMARY KEY (`Kompleti_idKompleti`, `Racun_idRacun`),
  INDEX `fk_Kompleti_has_Racun_Kompleti1_idx` (`Kompleti_idKompleti` ASC) VISIBLE,
  INDEX `fk_Postavke_Racun1_idx` (`Racun_idRacun` ASC) VISIBLE,
  CONSTRAINT `fk_Kompleti_has_Racun_Kompleti1`
    FOREIGN KEY (`Kompleti_idKompleti`)
    REFERENCES `mydb`.`Kompleti` (`idKompleti`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Postavke_Racun1`
    FOREIGN KEY (`Racun_idRacun`)
    REFERENCES `mydb`.`Racun` (`idRacun`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
